os_config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

os_availability_zone: nova
os_image: rhel-7.2
os_flavor: m1.small
os_network_name: direct
os_network_cidr: 10.12.48.0/24
os_key_pair: tcross

os_build_delay: 20
# Use public IP to connect to instances from Tower
os_use_public_IP: true

os_auth:
  project_name: "{{ lookup('env', 'OS_PROJECT') }}"
  auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
  username: "{{ lookup('env', 'OS_USERNAME') }}"
  password: "{{ lookup('env', 'OS_PASSWORD') }}"
