---
- name: Provision monitor compute instances
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Launch ceph monitor compute instances
      os_server:
        auth: "{{ os_auth }}"
        name: ceph-mon-{{ item }}
        auto_ip: "{{ os_use_public_IP }}"
        image: "{{ os_image }}"
        flavor: "{{ os_flavor }}"
        key_name: "{{ os_key_pair }}"
        nics:
          - net-name: "{{ os_network_name }}"
        security_groups:
          - ssh
          - ceph
        wait: no
        state: present
      with_sequence: start=0 end={{ mon_count - 1 }} stride=1

    - name: Wait a little while for instances to get out of BUILD state
      pause:
        seconds: "{{ os_build_delay }}"

    - name: Wait for all monitor compute instances to be ready
      os_server:
        auth: "{{ os_auth }}"
        name: ceph-mon-{{ item }}
        auto_ip: "{{ os_use_public_IP }}"
        image: "{{ os_image }}"
        flavor: "{{ os_flavor }}"
        key_name: "{{ os_key_pair }}"
        nics:
          - net-name: "{{ os_network_name }}"
        volumes:
          - ceph-storage-{{ item }}
        security_groups:
          - ssh
          - ceph
        wait: yes
        state: present
      with_sequence: start=0 end={{ mon_count - 1 }} stride=1
      register: ceph_mon_compute_instances

    - name: Add all provisioned monitor instances with public IP to inventory
      add_host:
        name: "{{ item['openstack']['name'] }}"
        groups: ceph,"{{ mon_group_name }}"
        ansible_host: "{{ item['openstack']['public_v4'] }}"
      with_items: "{{ ceph_mon_compute_instances.results }}"
      when: "{{ os_use_public_IP }}"

    - name: Add all provisioned monitor instances with private IP to inventory
      add_host:
        name: "{{ item['openstack']['name'] }}"
        groups: ceph,"{{ mon_group_name }}"
        ansible_host: "{{ item['openstack']['private_v4'] }}"
      with_items: "{{ ceph_mon_compute_instances.results }}"
      when: not "{{ os_use_public_IP }}"
