---
- name: Provision OSD compute instances and storage volumes
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Create storage volumes
      os_volume:
        auth: "{{ os_auth }}"
        display_name: ceph-storage-{{ item }}
        display_description: persistent ceph storage volume
        availability_zone: "{{ os_availability_zone }}"
        size: "{{ ceph_storage_volume_size }}"
        wait: no
        state: present
      with_sequence: start=0 end={{ osd_count - 1 }} stride=1

    - name: Wait for all storage volumes to be ready
      os_volume:
        auth: "{{ os_auth }}"
        display_name: ceph-storage-{{ item }}
        display_description: persistent ceph storage volume
        availability_zone: "{{ os_availability_zone }}"
        size: "{{ ceph_storage_volume_size }}"
        wait: yes
        state: present
      with_sequence: start=0 end={{ osd_count - 1 }} stride=1
      register: ceph_storage_volumes

    - name: Launch ceph OSD compute instances
      os_server:
        auth: "{{ os_auth }}"
        name: ceph-osd-{{ item }}
        auto_ip: "{{ os_use_public_IP }}"
        image: "{{ os_image }}"
        flavor: "{{ os_flavor }}"
        key_name: "{{ os_key_pair }}"
        nics:
          - net-name: "{{ os_network_name }}"
        volumes:
          - ceph-storage-{{ item }}
        security_groups:
          - ssh
          - ceph
        wait: no
        state: present
      with_sequence: start=0 end={{ osd_count - 1 }} stride=1

    - name: Wait a little while for instances to get out of BUILD state
      pause:
        seconds: "{{ os_build_delay }}"

    - name: Wait for all OSD compute instances to be ready
      os_server:
        auth: "{{ os_auth }}"
        name: ceph-osd-{{ item }}
        auto_ip: "{{ os_use_public_IP }}"
        image: "{{ os_image }}"
        flavor: "{{ os_flavor }}"
        key_name: "{{ os_key_pair }}"
        nics:
          - net-name: "{{ os_network_name }}"
        volumes:
          - ceph-storage-{{ item }}
        security_groups:
          - ssh
          - ceph
        wait: yes
        state: present
      with_sequence: start=0 end={{ osd_count - 1 }} stride=1
      register: ceph_osd_compute_instances

    - name: Print OSD Host information we have
      debug:
        var: ceph_osd_compute_instances.results

    - name: Add all provisioned monitor instances with public IP to inventory
      add_host:
        name: "{{ item['openstack']['name'] }}"
        groups: ceph,"{{ osd_group_name }}"
        ansible_host: "{{ item['openstack']['public_v4'] }}"
      with_items: "{{ ceph_mon_compute_instances.results }}"
      when: "{{ os_use_public_IP }}"

    - name: Add all provisioned monitor instances with private IP to inventory
      add_host:
        name: "{{ item['openstack']['name'] }}"
        groups: ceph,"{{ osd_group_name }}"
        ansible_host: "{{ item['openstack']['private_v4'] }}"
      with_items: "{{ ceph_mon_compute_instances.results }}"
      when: not "{{ os_use_public_IP }}"
